[project]
name = "bridge2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.16"
dependencies = [
    "altair>=5.5.0",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "streamlit>=1.50.0",
    "streamlit-autorefresh>=1.0.1",
]
